version: '3.4'

services:
  abritestask:
    image: abritestask:dev
    build:
      context: .
      dockerfile: AbritesTask/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
